logging:
  level:
    com.smalik.devservicebroker: DEBUG
    org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: ERROR
    org.springframework.data.convert.CustomConversions: ERROR

broker:
  cluster-domain: cluster.local
  namespace: service-broker
  services:
    - id: k-rabbit
      description: Dedicated RabbitMQ running on kubernetes
      tags:
        - rabbitmq
        - amqp
      plans:
        - id: k-rabbit-default
          name: default
          description: Small RabbitMQ message broker suitable for development purposes
    - id: k-mysql
      description: Dedicated MySQL running on kubernetes
      tags:
        - mysql
        - relational
        - database
      plans:
        - id: k-mysql-default
          name: default
          description: Small database suitable for development purposes
    - id: k-redis
      description: Dedicated Redis running on kubernetes
      tags:
        - redis
        - caching
      plans:
        - id: k-redis-default
          name: default
          description: Small redis server suitable for development purposes
    - id: k-elasticsearch
      description: Dedicated ElasticSearch running on kubernetes
      tags:
        - elasticsearch
        - search
      plans:
        - id: k-elasticsearch-default
          name: default
          description: Small ElasticSearch server suitable for development purposes
    - id: k-mongo
      description: Dedicated MongoDB running on kubernetes
      tags:
        - mongo
        - mongodb
        - nosql
        - database
      plans:
        - id: k-mongo-default
          name: default
          description: Small MongoDB server suitable for development purposes

