apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: elasticsearch
    name: {name}
spec:
  ports:
  - name: elasticsearch
    port: {port}
  clusterIP: None
  selector:
    type: elasticsearch
    name: {name}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: elasticsearch
    name: {name}
spec:
  selector:
    matchLabels:
      type: elasticsearch
      name: {name}
  serviceName: {name}
  replicas: 1
  template:
    metadata:
      labels:
        type: elasticsearch
        name: {name}
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
        ports:
        - name: elasticsearch
          containerPort: {port}
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms64m -Xmx64m"
        - name: network.host
          value: "0.0.0.0"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: {port}
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: {port}
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: {namespace}
      labels:
        type: elasticsearch
        name: {name}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
