apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: mongo
    name: {name}
spec:
  ports:
  - name: mongo
    port: {port}
  clusterIP: None
  selector:
    type: mongo
    name: {name}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: mongo
    name: {name}
spec:
  selector:
    matchLabels:
      type: mongo
      name: {name}
  serviceName: {name}
  replicas: 1
  template:
    metadata:
      labels:
        type: mongo
        name: {name}
    spec:
      containers:
      - name: mongo
        image: mongo:4
        args:
        - "--wiredTigerCacheSizeGB"
        - "0.125"
        ports:
        - name: mongo
          containerPort: {port}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {rootusername}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {rootpassword}
        - name: MONGO_INITDB_DATABASE
          value: {db}
        volumeMounts:
        - name: data
          mountPath: /data/db
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: {port}
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: {port}
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: {namespace}
      labels:
        type: mongo
        name: {name}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
