apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: mysql
    name: {name}
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    type: mysql
    name: {name}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: mysql
    name: {name}
spec:
  selector:
    matchLabels:
      type: mysql
      name: {name}
  serviceName: {name}
  replicas: 1
  template:
    metadata:
      labels:
        type: mysql
        name: {name}
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {rootpassword}
        - name: MYSQL_DATABASE
          value: db
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        livenessProbe:
          exec:
            command: ["mysqladmin", "-p${MYSQL_ROOT_PASSWORD}", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: {namespace}
      labels:
        type: mysql
        name: {name}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
