apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: postgres
    name: {name}
spec:
  ports:
  - name: postgres
    port: {port}
  clusterIP: None
  selector:
    type: postgres
    name: {name}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    type: postgres
    name: {name}
spec:
  selector:
    matchLabels:
      type: postgres
      name: {name}
  serviceName: {name}
  replicas: 1
  template:
    metadata:
      labels:
        type: postgres
        name: {name}
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_PASSWORD
          value: {rootpassword}
        ports:
        - name: postgres
          containerPort: {port}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: {namespace}
      labels:
        type: postgres
        name: {name}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
